services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-trainingsplan-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: pacr
      DB_USERNAME: pacr
      DB_PASSWORD: ${DB_PASSWORD}
      APP_CORS_ALLOWED_ORIGINS: http://localhost,http://localhost:4200
      STRAVA_REDIRECT_URI: http://localhost/api/strava/callback
      STRAVA_FRONTEND_URL: http://localhost
    networks:
      - mariadb_default
      - app_network

  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    container_name: smart-trainingsplan-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:

  mariadb_default:
      external: true