package com.trainingsplan.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.time.LocalDate;

/**
 * Aggregated daily training strain for a single user.
 * Recomputed whenever an {@link ActivityMetrics} record is saved for that day.
 * The combination of (user_id, date) is unique.
 */
@Entity
@Table(name = "daily_metrics",
       uniqueConstraints = @UniqueConstraint(
               name = "uq_daily_metrics_user_date",
               columnNames = {"user_id", "date"}))
public class DailyMetrics {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    @Column(name = "date", nullable = false)
    private LocalDate date;

    /** Sum of strain21 values for all activities on this day. */
    @Column(name = "daily_strain21")
    private Double dailyStrain21;

    /** Sum of TRIMP values for all activities on this day. */
    @Column(name = "daily_trimp")
    private Double dailyTrimp;

    /**
     * Rolling 7-day average Efficiency Factor (m/s per bpm).
     * NULL when no eligible activities in the 7-day window ending on {@code date}.
     */
    @Column(name = "ef7")
    private Double ef7;

    /**
     * Rolling 28-day average Efficiency Factor (m/s per bpm).
     * NULL when no eligible activities in the 28-day window ending on {@code date}.
     */
    @Column(name = "ef28")
    private Double ef28;

    /** 7-day sum of daily_strain21 ending on this date. */
    @Column(name = "acute7")
    private Double acute7;

    /**
     * 28-day sum of daily_strain21 / 4 — same scale as acute7 (= avg(28d) × 7).
     * NULL when all 28 days have zero strain.
     */
    @Column(name = "chronic28")
    private Double chronic28;

    /**
     * Acute:Chronic Workload Ratio = acute7 / chronic28.
     * NULL when chronic28 = 0.
     */
    @Column(name = "acwr")
    private Double acwr;

    /**
     * Load-zone flag: BLUE (&lt;0.8), GREEN (0.8–1.3), ORANGE (1.3–1.6), RED (&gt;1.6).
     * NULL when acwr is NULL.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "acwr_flag", length = 10)
    private AcwrFlag acwrFlag;

    /** Short German text describing the ACWR flag. NULL when acwr is NULL. */
    @Column(name = "acwr_message", length = 100)
    private String acwrMessage;

    /**
     * Readiness score 0–100 computed by the v1 heuristic.
     * Higher = more recovered; NULL until first computation.
     */
    @Column(name = "readiness_score")
    private Integer readinessScore;

    /**
     * Training recommendation derived from {@code readinessScore}.
     * NULL until first computation.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "recommendation", length = 10)
    private Recommendation recommendation;

    /**
     * JSON array (max 3 strings) explaining the readiness score deductions.
     * Example: ["Hohes ACWR","Hohe gestrige Belastung"]
     */
    @Column(name = "reasons_json", length = 500)
    private String reasonsJson;

    /**
     * Short coaching headline generated by {@link com.trainingsplan.service.CoachCardService}.
     * Example: "Easy day recommended"
     */
    @Column(name = "coach_title", length = 100)
    private String coachTitle;

    /**
     * JSON array of max 3 coaching bullet strings.
     * Example: ["Akute Belastung deutlich über deinem 4-Wochen-Niveau","Hohe HR-Drift → ..."]
     */
    @Column(name = "coach_bullets_json", length = 500)
    private String coachBulletsJson;

    public DailyMetrics() {}

    public Long getId() { return id; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) { this.date = date; }

    public Double getDailyStrain21() { return dailyStrain21; }
    public void setDailyStrain21(Double dailyStrain21) { this.dailyStrain21 = dailyStrain21; }

    public Double getDailyTrimp() { return dailyTrimp; }
    public void setDailyTrimp(Double dailyTrimp) { this.dailyTrimp = dailyTrimp; }

    public Double getEf7() { return ef7; }
    public void setEf7(Double ef7) { this.ef7 = ef7; }

    public Double getEf28() { return ef28; }
    public void setEf28(Double ef28) { this.ef28 = ef28; }

    public Double getAcute7() { return acute7; }
    public void setAcute7(Double acute7) { this.acute7 = acute7; }

    public Double getChronic28() { return chronic28; }
    public void setChronic28(Double chronic28) { this.chronic28 = chronic28; }

    public Double getAcwr() { return acwr; }
    public void setAcwr(Double acwr) { this.acwr = acwr; }

    public AcwrFlag getAcwrFlag() { return acwrFlag; }
    public void setAcwrFlag(AcwrFlag acwrFlag) { this.acwrFlag = acwrFlag; }

    public String getAcwrMessage() { return acwrMessage; }
    public void setAcwrMessage(String acwrMessage) { this.acwrMessage = acwrMessage; }

    public Integer getReadinessScore() { return readinessScore; }
    public void setReadinessScore(Integer readinessScore) { this.readinessScore = readinessScore; }

    public Recommendation getRecommendation() { return recommendation; }
    public void setRecommendation(Recommendation recommendation) { this.recommendation = recommendation; }

    public String getReasonsJson() { return reasonsJson; }
    public void setReasonsJson(String reasonsJson) { this.reasonsJson = reasonsJson; }

    public String getCoachTitle() { return coachTitle; }
    public void setCoachTitle(String coachTitle) { this.coachTitle = coachTitle; }

    public String getCoachBulletsJson() { return coachBulletsJson; }
    public void setCoachBulletsJson(String coachBulletsJson) { this.coachBulletsJson = coachBulletsJson; }
}
